@echo off
echo 🔄 Starting fresh server...

echo Killing any existing Node processes...
taskkill /F /IM node.exe >nul 2>&1

echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul

echo Starting working server...
node working-server.js
